# [![Build Status](https://travis-ci.org/dex4er/PureProxy.png?branch=master)](https://travis-ci.org/dex4er/PureProxy)

sudo: false
addons:
  apt:
    packages:
    - aspell-en
language: perl
perl:
  - "dev"
  - "5.22"
  - "5.8"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - cpanm --with-recommends --installdeps --notest --skip-satisfied git://github.com/dex4er/perl-DEXTER-Module-Skeleton
  - cpanm --with-recommends --installdeps --notest --skip-satisfied .
script:
  - ./Dist.SH
